// packages/odk-web-forms/vue/src/components/XFormInputControl.vue
<template>
  <!-- add non label  -->
  <TextWidget :control="control" :state="state" />
</template>

<script setup lang="ts">
import { InputDefinition } from '../../../src/lib/xform/body/control/InputDefinition';
import { ValueNodeState } from '../../../src/lib/xform/state/ValueNodeState';
import TextWidget from './TextWidget.vue';

defineProps<{ readonly control: InputDefinition, readonly state: ValueNodeState }>()
</script>

<style scoped></style>

// packages/odk-web-forms/src/components/XForm/controls/XFormInputControl.tsx
import { Show } from 'solid-js';
import type { InputState } from '../../../lib/xform/state/value/InputState.ts';
import { TextWidget } from '../../Widget/TextWidget.tsx';
import { XFormUnlabeledControl } from '../debugging/XFormUnlabeledInputControl.tsx';

interface XFormInputControlProps {
	readonly state: InputState;
}

export const XFormInputControl = (props: XFormInputControlProps) => {
	return (
		<>
			<Show when={props.state.bodyElement.label == null}>
				<XFormUnlabeledControl control={props.state.bodyElement} />
			</Show>
			<TextWidget state={props.state} />
		</>
	);
};
